GET https://jsonplaceholder.typicode.com/posts

###


POST https://jsonplaceholder.typicode.com/posts

Content-Type: application/json
[
{

"title":5555,
"body":22222
}
]
###

POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json
{

"title":5555,
"body":22222
}